foreground=#b7c5d3
background=#010813
cursor=#539afc

color0=#171d23   # black
color1=#ee3a43   # red
color2=#8bd49c   # green
color3=#d98e48   # yellow
color4=#539afc   # blue
color5=#b62d65   # magenta
color6=#008b94   # cyan
color7=#b7c5d3   # white

color8=#41505e   # brblack
color9=#d95468   # brred
color10=#3ad900  # brgreen
color11=#ebbf83  # bryellow
color12=#5ec4ff  # brblue
color13=#e27e8d  # brmagenta
color14=#70e1e8  # brcyan
color15=#ffffff  # brwhite
