cursor: #EBA96C
background: #201e19
foreground: #BCAC8F

# Black
color0:  #3a3830
color8:  #5f5f5f
# Red
color1:  #b38f8f
color9:  #D66848
# Green
color2:  #678E87
color10: #85a89f
# Yellow
color3:  #DB9833
color11: #DBAD49
# Blue
color4:  #798283
color12: #8fa3b3
# Magenta
color5:  #cc7f66
color13: #E08542
# Cyan
color6:  #75715E
color14: #7f7b66
# White
color7:  #BCAC8F
color15: #EBA96C
