cursor: #cdb2ff
background: #1b1e2b
foreground: #e4f3fa

# Black
color0:  #414357
color8:  #616377
# Red
color1:  #ff757f
color9:  #f67f81
# Green
color2:  #59d6b5
color10: #2df4c0
# Yellow
color3:  #ff9e7b
color11: #ffc777
# Blue
color4:  #ad82ed
color12: #b994f1
# Magenta
color5:  #ecb2f0
color13: #f77eae
# Cyan
color6:  #16fcf8
color14: #04d1f9
# White
color7:  #e9ecf1
color15: #eeffff
