cursor: #AEAFAD
# background: #2d3039
background: #1d2029
foreground: #b9c3df

# Black
color0:  #424552
color8:  #636369
# Red
color1:  #fb5f8e
color9:  #D16969
# Green
color2:  #1dc7a0
color10: #7de7c0
# Yellow
color3:  #D7BA7D
color11: #f8a257
# Blue
color4:  #38b4da
color12: #71c2d4
# Magenta
color5:  #ff7fb6
color13: #Df7fb6
# Cyan
color6:  #b894ff
color14: #c9b8ff
# White
color7:  #e9ecf1
color15: #edfbff
