foreground=#e0def4
background=#191724
cursor=#c4a7e7

color0=#26233a   # overlay (instead of muted gray)
color1=#eb6f92   # love
color2=#31748f   # pine
color3=#f6c177   # gold
color4=#9ccfd8   # foam
color5=#c4a7e7   # iris
color6=#95b1ac   # leaf
color7=#e0def4   # text

color8=#403d52   # highlight_med
color9=#eb6f92   # love
color10=#31748f  # pine
color11=#f6c177  # gold
color12=#9ccfd8  # foam
color13=#c4a7e7  # iris
color14=#95b1ac  # leaf
color15=#e0def4  # text
