cursor: #bfdbe1
background: #0f111b
foreground: #ecf0c1
# Black
color0:  #000000
color8:  #686f9a
# Red
color1:  #e33400
color9:  #c31400
# Green
color2:  #5ccc96
color10: #3cac76
# Yellow
color3:  #b3a1e6
color11: #9381c6
# Blue
color4:  #00a3cc
color12: #0083ac
# Magenta
color5:  #f2ce00
color13: #d2ae00
# Cyan
color6:  #7a5ccc
color14: #5a3cac
# White
color7:  #686f9a
color15: #f0f1ce
