cursor: #9DB0B4
# background: #152326
background: #000000
foreground: #DBD0C6

# Black
color0:  #234847
color8:  #314654
# Red
color1:  #fb5f8e
color9:  #D16969
# Green
color2:  #6FA791
color10: #9EBB9C
# Yellow
color3:  #FFD7AA
color11: #F7B982
# Blue
color4:  #86BFD0
color12: #A7CBEA
# Magenta
color5:  #B98DB4
color13: #D9ADD4
# Cyan
color6:  #79C2B6
color14: #87CBB1
# White
color7:  #D9D3CE
color15: #91A4AD
